# Generated by Django 2.2.5 on 2020-02-17 09:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20200217_0901'),
        ('helps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Helps',
            new_name='Help',
        ),
    ]
