# Generated by Django 2.2.5 on 2020-02-17 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helps', '0002_auto_20200217_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='help',
            old_name='name',
            new_name='user',
        ),
    ]
