# Generated by Django 2.2.5 on 2020-04-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helps', '0003_auto_20200217_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
