# Generated by Django 2.2.5 on 2020-04-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helps', '0004_auto_20200415_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='location',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
