# Generated by Django 2.2.5 on 2020-04-18 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200416_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lenght',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
    ]
